### ISSUE TITLE
add vulnerable marking to bottom block "randomly"

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#102]
Set a parameter in config for a random interval (as measured by game timer of #103 ) defaulting to 77. Every time timer crosses interval of 77, pick one existing 'bottom' block and mark it vulnerable (per story #97 )

Other stories will reconfig this interval (making it faster as score gets higher, making it slower if certain powerups are active)

**Comment by TraceyOnim** [comment]
@sparrell I would like to request for clarification on the following:
 - gametime counter in regards to the state of the game
 - 'bottom' block
 
Currently there is an existing  [PR](https://github.com/sFractal-Podii/quizquadaminos/pull/150)(Draft) that works as follows:

 - gametime counter increases with each clock time but only if the state of the game is playing and paused
 - when gametime counter crosses interval of 77 vulnerability marking is added to random 'bottom' block
 - grey/yellow is used to indicate vulnerability

![Peek 2021-03-25 21-38](https://user-images.githubusercontent.com/43263401/112526175-b547aa80-8db2-11eb-9311-f456012f1e91.gif)


Question 1: bottom
![image](https://user-images.githubusercontent.com/43263401/112524536-0060be00-8db1-11eb-8bcd-4e2e2a99a011.png)

From the image, I have numbered the blocks 1, 2, 3, 4. When you say add vulnerability to one existing bottom block, do you mean any random block(1, 2, 3, 4) at the 'bottom' can be marked vulnerable, or it's only block 1 or 2 that can be marked vulnerable?

Question 2: Gametime counter 
Should I consider the state of the game when increasing gametime counter with each clock time?

**Comment by sparrell** [comment]
@TraceyOnim: Good questions.

Q1 - bottom is 1-4. Ie the 'bottom' variable is the socket assigns.

Q2 - If I understand the question, you are asking about whether this counter should also 'pause' when game pauses. The answer to that is yes. The only reason it needs to be a separate counter is (1) so that it resets every time you add a vulnerability and (2) so that it only increments from clock ticks, not from points added due to answering questions or clearing rows

Question in return: is the 77 set as a parameter in config file? If not it should be, and I probably should set default to a larger number now that I see how fast you get to 77 (only about 5 blocks). Maybe 267 (I'm picking random, non-round numbers just to be ornery).

**Comment by TraceyOnim** [comment]
@sparrell , thank you for the clarification. 
To answer your question, yes the defaulting value will be added to the config file.
