### ISSUE TITLE
Powerups fontawesome icons

### ISSUE THREAD

**Issue by TraceyOnim** [sFractal-Podii/quizquadaminos#129]
Add the following powerup icons:

- Arrows for move (https://fontawesome.com/icons/arrows-alt?style=solid)
- eraser for clearblocks (https://fontawesome.com/icons/eraser?style=solid)
- fast-forward for speedup (https://fontawesome.com/icons/fast-forward?style=solid)
- fastbackwards for slow down (https://fontawesome.com/icons/fast-backward?style=solid)
- Wrench for fixing a vulnerability (https://fontawesome.com/icons/wrench?style=solid)
- screwdriver for fixing a license error (https://fontawesome.com/icons/screwdriver?style=solid)
- 3/4 battery for reducing vulnerability/license-error arrival rates (https://fontawesome.com/icons/battery-three-quarters?style=solid)
- Toolbox (https://fontawesome.com/icons/toolbox?style=solid) for autofixing all vulnerabilities
- Tools https://fontawesome.com/icons/tools?style=solid 
- Superpowers (https://fontawesome.com/icons/superpowers?style=brands)
- Plug (https://fontawesome.com/icons/plug?style=solid)
- Bomb (https://fontawesome.com/icons/bomb?style=solid)
- File-contract (https://fontawesome.com/icons/file-contract?style=solid)
- ID card (https://fontawesome.com/icons/id-card?style=regular)
- Prescription (https://fontawesome.com/icons/file-prescription?style=solid)

Note this story just makes the icons. Separate stories for the function the icons exhibit

**Comment by sparrell** [comment]
done and in rc
