### ISSUE TITLE
leaderboard: top bricks and top questions

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#284]
current leaderboard lists top ten games by score.

this story keeps 'by score' as 'tab 1' and adds two tabs - 'by bricks' and 'by questions'. 

If you click on any of 3 'tabs' it shows that 'top 10'. Note it is not just a resort since I might have a score in 20th place by score (ie not on table) but 5th place (ie is on table) by questions answered.

For all 3 tabs - if a tie (ie two games with same score), the game with the earlier 'end time' gets listed first.

**Comment by sigu** [comment]
I worked on the difference between the `start_time` and `end_time` so the one who took the shortest time playing comes before those who took longer
