### ISSUE TITLE
add another 'conference' leaderboard

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#355]
currently there is an 'all time leaderboard' and a 'contest leaderboard'. Proposal is to add a third leaderboard called 'conference leaderboard'.

- all time leaderboard stays forever
- conf leaderboard is renamed (this one called "BSides") and zero'd for each conference and freezes at end of conference. Countdown to start of conference, then countdown to end of conf
- contest leaderboard is only for timeframe (30 min in this case). Countdown to start of contest, then countdown to end of context

**Comment by TraceyOnim** [comment]
- [x] Enable admin to create a contest
- [x] Display created contest(s) on the contest board
- [x] Show start_time when the contest is started
- [x] Enable the timer to start counting independently when the start button is clicked
- [ ] Enable admin to pause contest timer
- [ ] Enable admin to stop contest timer
- [ ] Display contest end time when the timer is stopped
- [ ] Display the final result button when the timer is stopped
- [ ] Enable admin to reset the timer
- [ ] Display contest in a sorted manner
