### ISSUE TITLE
fix 'sticky' bug

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#364]
may be one problem or may be two problems.
when answering openchain Q you get a fixlicense tool.
click on fixlicense tool when there are no licenses to fix.
click on some blocks (bottom blocks, white space in middle blocks, following quad blocks). Nothing happens (which is correct). Hit space bar to continue. Block that was falling stays stuck in midair. I think may be in 'sticky' (ie fix license would keep working) but couldn't verify.

Do similar with OpenC2 'move block' (except don't click on a valid block). Hit space bar. Might end up sticky.

DItto 'delete block' and fixvuln

**Comment by sigu** [comment]
Following the steps above does not lead to the bug. I have tried reproducing it with
- delete block
- fix license

Below is a video of my steps

https://user-images.githubusercontent.com/584211/125262095-8e35ca00-e30a-11eb-8d17-581e1f44b0aa.mov
