### ISSUE TITLE
 "How to Play"

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#53]
Move "How to Play" off of home page and off of playing page. Make a "how to play" page and put (open in new window) links to it on homepage and playing page

**Comment by sparrell** [comment]
note I put some how to play info (about final game we aren't at yet) in https://github.com/sFractal-Podii/quizquadaminos/blob/main/docs/HowToPlay.md

**Comment by TraceyOnim** [comment]
> note I put some how to play info (about final game we aren't at yet) in https://github.com/sFractal-Podii/quizquadaminos/blob/main/docs/HowToPlay.md

@WanjikuMac is has moved the how to play in another page . I have a question on this , are we supposed to add the info as it is provided here https://github.com/sFractal-Podii/quizquadaminos/blob/main/docs/HowToPlay.md?

**Comment by WanjikuMac** [comment]
This is how it's currently implemented on #85

**Comment by TraceyOnim** [comment]
Done
