### ISSUE TITLE
select questions in order instead of at random

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#55]
currently lib/quadquizaminos/qna.ex choose_file uses Enum.random. Note there is a bug since I get the same question each time during a game (new question each new game). Instead of fixing that bug, enhance with following feature

Instead keep track of a counter per topic and increment with each question correctly answered.
eg start at 0 for sbom, 0 for openc2. User selects sbom, and gets asked sbom question 1 which after answering the sbom counter moves to 1 and the openc2 counter stays at 0. Then next time user gets an sbom question, question 2 gets asked. counters reset in each game.

I assume will involve adding some assigns for these counters

**Comment by sparrell** [comment]
When a card gets moved to code review, a comment should be included which points to which branch or PR the code is committed to

**Comment by TraceyOnim** [comment]
Done
