### ISSUE TITLE
Scoring Points via questions

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#87]
Currently answering questions incorrectly just returns you to question and answering questions correctly just returns you to game. This story as two parts:
- if answer correctly, increase score by R points and then continue. 
- if answer incorrectly, decrease score by W points and then go back to question.
For this story R (ie for Right answer) can be configured to 25 and W (for Wrong answer) configured to 5 points.

In a future story make R & W set per question on the QNA markdown page. This will allow us to make harder questions worth more points and give incentive to get thru the easy ones to get to the ones worth alot more

Note score is equal to counter, so just increment counter to increase score

**Comment by TraceyOnim** [comment]
done

**Comment by TraceyOnim** [comment]
Done
