### ISSUE TITLE
is CoordModalComponent used?

### ISSUE THREAD

**Issue by sparrell** [sFractal-Podii/quizquadaminos#994]

**Comment by sparrell** [comment]
https://github.com/sFractal-Podii/quizquadaminos/blob/develop/lib/quadblockquiz_web/live/coord_modal_component.ex
is CoordModalComponent used anywhere?

**Comment by WanjikuMac** [comment]
Confirmed, not in use anywhere, a different approach was used to fix what it was supposed to fix
